version: '3.8'

services:
  rust:
    build:
      dockerfile: ".docker/rust.dockerfile"
    container_name: "le-saviez-vous"
    ports:
      - $ROCKET_OUTER_PORT:8000
    volumes:
      - ".:/var/www"
    working_dir: "/var/www"
    command: '$ROCKET_COMMAND'
  