version: '3.8'

services:
  rust:
    image: rust:latest
    container_name: "le-saviez-vous"
    ports:
      - $ROCKET_OUTER_PORT:8000
    volumes:
      - ".:/var/www"
    working_dir: "/var/www"
    command: 'cargo run --release'